// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dbp.proto

package dbp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Msg int32

const (
	Msg_CONNECT   Msg = 0
	Msg_CONNECTED Msg = 1
	Msg_FAILED    Msg = 2
	Msg_PING      Msg = 3
	Msg_PONG      Msg = 4
	Msg_SUB       Msg = 5
	Msg_UNSUB     Msg = 6
	Msg_NOSUB     Msg = 7
	Msg_READY     Msg = 8
	Msg_ADDED     Msg = 9
	Msg_CHANGED   Msg = 10
	Msg_REMOVED   Msg = 11
	Msg_METHOD    Msg = 12
	Msg_RESULT    Msg = 13
	Msg_ERROR     Msg = 14
)

var Msg_name = map[int32]string{
	0:  "CONNECT",
	1:  "CONNECTED",
	2:  "FAILED",
	3:  "PING",
	4:  "PONG",
	5:  "SUB",
	6:  "UNSUB",
	7:  "NOSUB",
	8:  "READY",
	9:  "ADDED",
	10: "CHANGED",
	11: "REMOVED",
	12: "METHOD",
	13: "RESULT",
	14: "ERROR",
}
var Msg_value = map[string]int32{
	"CONNECT":   0,
	"CONNECTED": 1,
	"FAILED":    2,
	"PING":      3,
	"PONG":      4,
	"SUB":       5,
	"UNSUB":     6,
	"NOSUB":     7,
	"READY":     8,
	"ADDED":     9,
	"CHANGED":   10,
	"REMOVED":   11,
	"METHOD":    12,
	"RESULT":    13,
	"ERROR":     14,
}

func (x Msg) String() string {
	return proto.EnumName(Msg_name, int32(x))
}
func (Msg) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dbp_591cef42ea6196df, []int{0}
}

type Base struct {
	Msg                  Msg      `protobuf:"varint,1,opt,name=msg,proto3,enum=dbp.Msg" json:"msg,omitempty"`
	Object               *any.Any `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Base) Reset()         { *m = Base{} }
func (m *Base) String() string { return proto.CompactTextString(m) }
func (*Base) ProtoMessage()    {}
func (*Base) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbp_591cef42ea6196df, []int{0}
}
func (m *Base) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Base.Unmarshal(m, b)
}
func (m *Base) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Base.Marshal(b, m, deterministic)
}
func (dst *Base) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Base.Merge(dst, src)
}
func (m *Base) XXX_Size() int {
	return xxx_messageInfo_Base.Size(m)
}
func (m *Base) XXX_DiscardUnknown() {
	xxx_messageInfo_Base.DiscardUnknown(m)
}

var xxx_messageInfo_Base proto.InternalMessageInfo

func (m *Base) GetMsg() Msg {
	if m != nil {
		return m.Msg
	}
	return Msg_CONNECT
}

func (m *Base) GetObject() *any.Any {
	if m != nil {
		return m.Object
	}
	return nil
}

type Connect struct {
	Session              string              `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Version              int32               `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Client               string              `protobuf:"bytes,3,opt,name=client,proto3" json:"client,omitempty"`
	Udata                map[string]*any.Any `protobuf:"bytes,4,rep,name=udata,proto3" json:"udata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Connect) Reset()         { *m = Connect{} }
func (m *Connect) String() string { return proto.CompactTextString(m) }
func (*Connect) ProtoMessage()    {}
func (*Connect) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbp_591cef42ea6196df, []int{1}
}
func (m *Connect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connect.Unmarshal(m, b)
}
func (m *Connect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connect.Marshal(b, m, deterministic)
}
func (dst *Connect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connect.Merge(dst, src)
}
func (m *Connect) XXX_Size() int {
	return xxx_messageInfo_Connect.Size(m)
}
func (m *Connect) XXX_DiscardUnknown() {
	xxx_messageInfo_Connect.DiscardUnknown(m)
}

var xxx_messageInfo_Connect proto.InternalMessageInfo

func (m *Connect) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func (m *Connect) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Connect) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

func (m *Connect) GetUdata() map[string]*any.Any {
	if m != nil {
		return m.Udata
	}
	return nil
}

type Connected struct {
	Session              string   `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Connected) Reset()         { *m = Connected{} }
func (m *Connected) String() string { return proto.CompactTextString(m) }
func (*Connected) ProtoMessage()    {}
func (*Connected) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbp_591cef42ea6196df, []int{2}
}
func (m *Connected) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connected.Unmarshal(m, b)
}
func (m *Connected) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connected.Marshal(b, m, deterministic)
}
func (dst *Connected) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connected.Merge(dst, src)
}
func (m *Connected) XXX_Size() int {
	return xxx_messageInfo_Connected.Size(m)
}
func (m *Connected) XXX_DiscardUnknown() {
	xxx_messageInfo_Connected.DiscardUnknown(m)
}

var xxx_messageInfo_Connected proto.InternalMessageInfo

func (m *Connected) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

type Failed struct {
	Reason               string   `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	Session              string   `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	Version              []int32  `protobuf:"varint,3,rep,packed,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Failed) Reset()         { *m = Failed{} }
func (m *Failed) String() string { return proto.CompactTextString(m) }
func (*Failed) ProtoMessage()    {}
func (*Failed) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbp_591cef42ea6196df, []int{3}
}
func (m *Failed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Failed.Unmarshal(m, b)
}
func (m *Failed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Failed.Marshal(b, m, deterministic)
}
func (dst *Failed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Failed.Merge(dst, src)
}
func (m *Failed) XXX_Size() int {
	return xxx_messageInfo_Failed.Size(m)
}
func (m *Failed) XXX_DiscardUnknown() {
	xxx_messageInfo_Failed.DiscardUnknown(m)
}

var xxx_messageInfo_Failed proto.InternalMessageInfo

func (m *Failed) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Failed) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func (m *Failed) GetVersion() []int32 {
	if m != nil {
		return m.Version
	}
	return nil
}

type Ping struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbp_591cef42ea6196df, []int{4}
}
func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (dst *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(dst, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Pong struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbp_591cef42ea6196df, []int{5}
}
func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (dst *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(dst, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Sub struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sub) Reset()         { *m = Sub{} }
func (m *Sub) String() string { return proto.CompactTextString(m) }
func (*Sub) ProtoMessage()    {}
func (*Sub) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbp_591cef42ea6196df, []int{6}
}
func (m *Sub) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sub.Unmarshal(m, b)
}
func (m *Sub) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sub.Marshal(b, m, deterministic)
}
func (dst *Sub) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sub.Merge(dst, src)
}
func (m *Sub) XXX_Size() int {
	return xxx_messageInfo_Sub.Size(m)
}
func (m *Sub) XXX_DiscardUnknown() {
	xxx_messageInfo_Sub.DiscardUnknown(m)
}

var xxx_messageInfo_Sub proto.InternalMessageInfo

func (m *Sub) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Sub) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Unsub struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Unsub) Reset()         { *m = Unsub{} }
func (m *Unsub) String() string { return proto.CompactTextString(m) }
func (*Unsub) ProtoMessage()    {}
func (*Unsub) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbp_591cef42ea6196df, []int{7}
}
func (m *Unsub) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Unsub.Unmarshal(m, b)
}
func (m *Unsub) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Unsub.Marshal(b, m, deterministic)
}
func (dst *Unsub) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Unsub.Merge(dst, src)
}
func (m *Unsub) XXX_Size() int {
	return xxx_messageInfo_Unsub.Size(m)
}
func (m *Unsub) XXX_DiscardUnknown() {
	xxx_messageInfo_Unsub.DiscardUnknown(m)
}

var xxx_messageInfo_Unsub proto.InternalMessageInfo

func (m *Unsub) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Nosub struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nosub) Reset()         { *m = Nosub{} }
func (m *Nosub) String() string { return proto.CompactTextString(m) }
func (*Nosub) ProtoMessage()    {}
func (*Nosub) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbp_591cef42ea6196df, []int{8}
}
func (m *Nosub) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nosub.Unmarshal(m, b)
}
func (m *Nosub) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nosub.Marshal(b, m, deterministic)
}
func (dst *Nosub) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nosub.Merge(dst, src)
}
func (m *Nosub) XXX_Size() int {
	return xxx_messageInfo_Nosub.Size(m)
}
func (m *Nosub) XXX_DiscardUnknown() {
	xxx_messageInfo_Nosub.DiscardUnknown(m)
}

var xxx_messageInfo_Nosub proto.InternalMessageInfo

func (m *Nosub) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Nosub) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Ready struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ready) Reset()         { *m = Ready{} }
func (m *Ready) String() string { return proto.CompactTextString(m) }
func (*Ready) ProtoMessage()    {}
func (*Ready) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbp_591cef42ea6196df, []int{9}
}
func (m *Ready) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ready.Unmarshal(m, b)
}
func (m *Ready) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ready.Marshal(b, m, deterministic)
}
func (dst *Ready) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ready.Merge(dst, src)
}
func (m *Ready) XXX_Size() int {
	return xxx_messageInfo_Ready.Size(m)
}
func (m *Ready) XXX_DiscardUnknown() {
	xxx_messageInfo_Ready.DiscardUnknown(m)
}

var xxx_messageInfo_Ready proto.InternalMessageInfo

func (m *Ready) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Added struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Object               *any.Any `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Added) Reset()         { *m = Added{} }
func (m *Added) String() string { return proto.CompactTextString(m) }
func (*Added) ProtoMessage()    {}
func (*Added) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbp_591cef42ea6196df, []int{10}
}
func (m *Added) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Added.Unmarshal(m, b)
}
func (m *Added) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Added.Marshal(b, m, deterministic)
}
func (dst *Added) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Added.Merge(dst, src)
}
func (m *Added) XXX_Size() int {
	return xxx_messageInfo_Added.Size(m)
}
func (m *Added) XXX_DiscardUnknown() {
	xxx_messageInfo_Added.DiscardUnknown(m)
}

var xxx_messageInfo_Added proto.InternalMessageInfo

func (m *Added) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Added) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Added) GetObject() *any.Any {
	if m != nil {
		return m.Object
	}
	return nil
}

type Changed struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Object               *any.Any `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Changed) Reset()         { *m = Changed{} }
func (m *Changed) String() string { return proto.CompactTextString(m) }
func (*Changed) ProtoMessage()    {}
func (*Changed) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbp_591cef42ea6196df, []int{11}
}
func (m *Changed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Changed.Unmarshal(m, b)
}
func (m *Changed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Changed.Marshal(b, m, deterministic)
}
func (dst *Changed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Changed.Merge(dst, src)
}
func (m *Changed) XXX_Size() int {
	return xxx_messageInfo_Changed.Size(m)
}
func (m *Changed) XXX_DiscardUnknown() {
	xxx_messageInfo_Changed.DiscardUnknown(m)
}

var xxx_messageInfo_Changed proto.InternalMessageInfo

func (m *Changed) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Changed) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Changed) GetObject() *any.Any {
	if m != nil {
		return m.Object
	}
	return nil
}

type Removed struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Object               *any.Any `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Removed) Reset()         { *m = Removed{} }
func (m *Removed) String() string { return proto.CompactTextString(m) }
func (*Removed) ProtoMessage()    {}
func (*Removed) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbp_591cef42ea6196df, []int{12}
}
func (m *Removed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Removed.Unmarshal(m, b)
}
func (m *Removed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Removed.Marshal(b, m, deterministic)
}
func (dst *Removed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Removed.Merge(dst, src)
}
func (m *Removed) XXX_Size() int {
	return xxx_messageInfo_Removed.Size(m)
}
func (m *Removed) XXX_DiscardUnknown() {
	xxx_messageInfo_Removed.DiscardUnknown(m)
}

var xxx_messageInfo_Removed proto.InternalMessageInfo

func (m *Removed) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Removed) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Removed) GetObject() *any.Any {
	if m != nil {
		return m.Object
	}
	return nil
}

type Method struct {
	Method               string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Params               *any.Any `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Method) Reset()         { *m = Method{} }
func (m *Method) String() string { return proto.CompactTextString(m) }
func (*Method) ProtoMessage()    {}
func (*Method) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbp_591cef42ea6196df, []int{13}
}
func (m *Method) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Method.Unmarshal(m, b)
}
func (m *Method) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Method.Marshal(b, m, deterministic)
}
func (dst *Method) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Method.Merge(dst, src)
}
func (m *Method) XXX_Size() int {
	return xxx_messageInfo_Method.Size(m)
}
func (m *Method) XXX_DiscardUnknown() {
	xxx_messageInfo_Method.DiscardUnknown(m)
}

var xxx_messageInfo_Method proto.InternalMessageInfo

func (m *Method) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Method) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Method) GetParams() *any.Any {
	if m != nil {
		return m.Params
	}
	return nil
}

type Result struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Error                string     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Result               []*any.Any `protobuf:"bytes,3,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbp_591cef42ea6196df, []int{14}
}
func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (dst *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(dst, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Result) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Result) GetResult() []*any.Any {
	if m != nil {
		return m.Result
	}
	return nil
}

type Error struct {
	Reason               string   `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	Explain              string   `protobuf:"bytes,2,opt,name=explain,proto3" json:"explain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbp_591cef42ea6196df, []int{15}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Error) GetExplain() string {
	if m != nil {
		return m.Explain
	}
	return ""
}

func init() {
	proto.RegisterType((*Base)(nil), "dbp.Base")
	proto.RegisterType((*Connect)(nil), "dbp.Connect")
	proto.RegisterMapType((map[string]*any.Any)(nil), "dbp.Connect.UdataEntry")
	proto.RegisterType((*Connected)(nil), "dbp.Connected")
	proto.RegisterType((*Failed)(nil), "dbp.Failed")
	proto.RegisterType((*Ping)(nil), "dbp.Ping")
	proto.RegisterType((*Pong)(nil), "dbp.Pong")
	proto.RegisterType((*Sub)(nil), "dbp.Sub")
	proto.RegisterType((*Unsub)(nil), "dbp.Unsub")
	proto.RegisterType((*Nosub)(nil), "dbp.Nosub")
	proto.RegisterType((*Ready)(nil), "dbp.Ready")
	proto.RegisterType((*Added)(nil), "dbp.Added")
	proto.RegisterType((*Changed)(nil), "dbp.Changed")
	proto.RegisterType((*Removed)(nil), "dbp.Removed")
	proto.RegisterType((*Method)(nil), "dbp.Method")
	proto.RegisterType((*Result)(nil), "dbp.Result")
	proto.RegisterType((*Error)(nil), "dbp.Error")
	proto.RegisterEnum("dbp.Msg", Msg_name, Msg_value)
}

func init() { proto.RegisterFile("dbp.proto", fileDescriptor_dbp_591cef42ea6196df) }

var fileDescriptor_dbp_591cef42ea6196df = []byte{
	// 587 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xdf, 0x4e, 0xdb, 0x30,
	0x14, 0xc6, 0x97, 0xb8, 0x49, 0xe9, 0xe9, 0x40, 0x96, 0x85, 0xa0, 0xe3, 0xaa, 0x8a, 0x34, 0x89,
	0xa1, 0x51, 0x24, 0x76, 0xb3, 0xed, 0xae, 0x34, 0xe6, 0x8f, 0x44, 0x13, 0x64, 0xda, 0x49, 0x68,
	0xd3, 0x24, 0x87, 0x78, 0x21, 0x5b, 0x1a, 0x57, 0x49, 0x8a, 0xd6, 0xe7, 0xda, 0xab, 0xec, 0x81,
	0x26, 0x3b, 0x2e, 0x45, 0x03, 0x2a, 0x6e, 0xb8, 0xfb, 0xbe, 0x73, 0x3e, 0xff, 0x4e, 0xec, 0x1c,
	0x68, 0xc5, 0xd1, 0xb4, 0x37, 0x2d, 0x64, 0x25, 0x09, 0x8a, 0xa3, 0xe9, 0xce, 0x9b, 0x44, 0xca,
	0x24, 0x13, 0x07, 0xba, 0x14, 0xcd, 0x7e, 0x1c, 0xf0, 0x7c, 0x5e, 0xf7, 0xbd, 0x0b, 0x68, 0x1c,
	0xf1, 0x52, 0x90, 0x1d, 0x40, 0x93, 0x32, 0xe9, 0x58, 0x5d, 0x6b, 0x77, 0xe3, 0x70, 0xad, 0xa7,
	0x00, 0xc3, 0x32, 0x61, 0xaa, 0x48, 0xde, 0x83, 0x2b, 0xa3, 0x9f, 0xe2, 0xba, 0xea, 0xd8, 0x5d,
	0x6b, 0xb7, 0x7d, 0xb8, 0xd9, 0xab, 0x79, 0xbd, 0x05, 0xaf, 0xd7, 0xcf, 0xe7, 0xcc, 0x64, 0xbc,
	0xbf, 0x16, 0x34, 0x07, 0x32, 0xcf, 0xc5, 0x75, 0x45, 0x3a, 0xd0, 0x2c, 0x45, 0x59, 0xa6, 0x32,
	0xd7, 0xe4, 0x16, 0x5b, 0x58, 0xd5, 0xb9, 0x15, 0x85, 0xee, 0x28, 0xa8, 0xc3, 0x16, 0x96, 0x6c,
	0x81, 0x7b, 0x9d, 0xa5, 0x22, 0xaf, 0x3a, 0x48, 0x1f, 0x31, 0x8e, 0xec, 0x83, 0x33, 0x8b, 0x79,
	0xc5, 0x3b, 0x8d, 0x2e, 0xda, 0x6d, 0x1f, 0x6e, 0xeb, 0x6f, 0x34, 0x83, 0x7a, 0x63, 0xd5, 0xa1,
	0x79, 0x55, 0xcc, 0x59, 0x9d, 0xda, 0x09, 0x00, 0x96, 0x45, 0x82, 0x01, 0xfd, 0x12, 0x73, 0xf3,
	0x11, 0x4a, 0x92, 0x3d, 0x70, 0x6e, 0x79, 0x36, 0x13, 0x2b, 0xef, 0x54, 0x47, 0x3e, 0xdb, 0x1f,
	0x2d, 0xef, 0x2d, 0xb4, 0xcc, 0x30, 0x11, 0x3f, 0x7d, 0x2f, 0x6f, 0x04, 0xee, 0x31, 0x4f, 0x33,
	0x11, 0xab, 0x7b, 0x14, 0x82, 0x97, 0x77, 0x11, 0xe3, 0xee, 0x9f, 0xb5, 0x9f, 0x7c, 0x13, 0xd4,
	0x45, 0xf7, 0xde, 0xc4, 0xdb, 0x82, 0xc6, 0x45, 0x9a, 0x27, 0x64, 0x03, 0xec, 0x34, 0x36, 0x3c,
	0x3b, 0x8d, 0x75, 0x5d, 0x3e, 0x52, 0x7f, 0x07, 0xe8, 0x72, 0x16, 0xfd, 0x5f, 0x26, 0x04, 0x1a,
	0x39, 0x9f, 0x08, 0x33, 0x57, 0x6b, 0x6f, 0x1b, 0x9c, 0x71, 0x5e, 0x3e, 0x0c, 0x7b, 0xfb, 0xe0,
	0x04, 0xf2, 0x91, 0x06, 0xd9, 0x04, 0x47, 0x14, 0x85, 0x2c, 0x0c, 0xa6, 0x36, 0x8a, 0xc3, 0x04,
	0x8f, 0xe7, 0x0f, 0x38, 0x57, 0xe0, 0xf4, 0xe3, 0x58, 0x2c, 0xa7, 0x5b, 0xcb, 0xe9, 0x26, 0x6c,
	0xdf, 0xb1, 0x97, 0xab, 0x86, 0x9e, 0xb1, 0x6a, 0x5f, 0xa1, 0x39, 0xb8, 0xe1, 0x79, 0xf2, 0x52,
	0x70, 0x26, 0x26, 0xf2, 0xf6, 0x45, 0xe0, 0xdf, 0xc1, 0x1d, 0x8a, 0xea, 0x46, 0xea, 0x35, 0x99,
	0x68, 0xb5, 0x58, 0x93, 0xda, 0x3d, 0xc6, 0x9f, 0xf2, 0x82, 0x4f, 0xca, 0xd5, 0xfc, 0x3a, 0xe3,
	0x7d, 0x03, 0x97, 0x89, 0x72, 0x96, 0x55, 0xcf, 0xfb, 0x7b, 0x8a, 0x5e, 0xe8, 0xbc, 0xde, 0xbc,
	0x27, 0xe9, 0x75, 0xc6, 0xfb, 0x04, 0x0e, 0xd5, 0xc7, 0x56, 0xec, 0xb8, 0xf8, 0x3d, 0xcd, 0x78,
	0x7a, 0xb7, 0xe3, 0xc6, 0xee, 0xfd, 0xb1, 0x00, 0x0d, 0xcb, 0x84, 0xb4, 0xa1, 0x39, 0x08, 0x83,
	0x80, 0x0e, 0x46, 0xf8, 0x15, 0x59, 0x87, 0x96, 0x31, 0xd4, 0xc7, 0x16, 0x01, 0x70, 0x8f, 0xfb,
	0x67, 0xe7, 0xd4, 0xc7, 0x36, 0x59, 0x83, 0xc6, 0xc5, 0x59, 0x70, 0x82, 0x91, 0x56, 0x61, 0x70,
	0x82, 0x1b, 0xa4, 0x09, 0xe8, 0x72, 0x7c, 0x84, 0x1d, 0xd2, 0x02, 0x67, 0x1c, 0x28, 0xe9, 0x2a,
	0x19, 0x84, 0x4a, 0x36, 0x95, 0x64, 0xb4, 0xef, 0x5f, 0xe1, 0x35, 0x25, 0xfb, 0xbe, 0x4f, 0x7d,
	0xdc, 0xd2, 0x03, 0x4f, 0xfb, 0xc1, 0x09, 0xf5, 0x31, 0x28, 0xc3, 0xe8, 0x30, 0xfc, 0x42, 0x7d,
	0xdc, 0x56, 0xe3, 0x86, 0x74, 0x74, 0x1a, 0xfa, 0xf8, 0xb5, 0xd2, 0x8c, 0x5e, 0x8e, 0xcf, 0x47,
	0x78, 0x5d, 0x1d, 0xa6, 0x8c, 0x85, 0x0c, 0x6f, 0x44, 0xae, 0x7e, 0x86, 0x0f, 0xff, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xb5, 0x61, 0x33, 0x8b, 0x59, 0x05, 0x00, 0x00,
}
