version: 2
jobs:
  build:
    working_directory: /go/src/github.com/lomocoin/lws
    docker:
      - image: circleci/golang:1.10
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: test
      - image: eclipse-mosquitto:1.4.12
      - image: circleci/redis:4.0.11
        environment:
          REDIS_URL: 127.0.0.1:6379
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run:
          name: Wait for DB
          # preinstalled in circleci/* docker image
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Wait for redis
          # preinstalled in circleci/* docker image
          command: dockerize -wait tcp://127.0.0.1:6379 -timeout 1m
      - run: go test -v -cover ./...
