version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.11
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: test
      - image: eclipse-mosquitto:1.4.12
      - image: "rabbitmq:3-management"
        environment:
          RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
          RABBITMQ_DEFAULT_USER: "rabbitmq"
          RABBITMQ_DEFAULT_PASS: "rabbitmq"
          RABBITMQ_DEFAULT_VHOST: "/"
      - image: circleci/redis:4.0.11
    steps:
      - checkout
      # - restore_cache:
      #     key: v1-dependencies-{{ checksum "go.sum" }}
      - run: go mod download
      # - save_cache:
      #     key: v1-dependencies-{{ checksum "go.sum" }}
      #     paths:
      #       - vendor
      - run:
          name: Wait for DB
          # preinstalled in circleci/* docker image
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: Wait for redis
          # preinstalled in circleci/* docker image
          command: dockerize -wait tcp://127.0.0.1:6379 -timeout 1m
      - run:
          name: Unit test
          command: go test -v -cover -p=1 ./...
      - run:
          name: Build entries to version binary
          command: |
            mkdir -p bin
            [[ $CIRCLE_TAG ]] && VERSION=$CIRCLE_TAG || VERSION=$CIRCLE_BRANCH
            GOOS=linux GOARCH=amd64 go build -o "bin/gateway-$VERSION" cmd/gateway/main.go
            GOOS=linux GOARCH=amd64 go build -o "bin/stream-$VERSION" cmd/stream/main.go
      - persist_to_workspace:
          root: .
          paths:
            - bin

  release:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          # use "." not "bin" which including "bin"
          at: .
      - run: go get github.com/tcnksm/ghr
      - run:
          name: Publish Github release
          command: |
            [[ $CIRCLE_TAG ]] && VERSION=$CIRCLE_TAG || VERSION=$CIRCLE_BRANCH
            ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME -c $CIRCLE_SHA1 -delete $VERSION bin

  deploy:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: bin
      - add_ssh_keys:
          fingerprints:
            - "b3:71:c5:88:0f:b0:ef:d6:62:98:3c:0a:7e:37:a6:46"
      - run:
          name: Delpoy via SSH
          command: |
            scp -P $TEST_SSH_PORT -r bin $TEST_SSH_USER@$TEST_SSH_HOST:~/projects/fnfn/lws/

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            # tags must be added here to trigger other job when tags filters defined
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - /^test/
            tags:
              only: /.*/
