version: 2
jobs:
  build:
    working_directory: /go/src/github.com/lomocoin/lws
    docker:
      - image: circleci/golang:1.10
      - image: eclipse/mosquitto:1.4.12
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v -cover ./...
